---
# Configure airflow

- name: service is enabled and started
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  become: true
  loop: "{{ airflow_services_enable }}"
  when: airflow_enable_service
